name: CI

on:
  push:
    branches:
      - master
      - test-http
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version: ['2.5.x', '2.6.x']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Start httpbin container
      run: docker run -p 8080:80 kennethreitz/httpbin
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run test
      run: bundle exec rspec
